Remove chain service polling
The polling feature is currently unused. Our unit test is occasionally flagging
an issue with either the polling feature or the polling unit test.

=== RUN   TestConcludeSimulatedBackendChainServiceWithPolling
    simulated_backend_chainservice_test.go:169: Received event did not match expectation; (-want +got):
          any(
        - 	chainservice.ConcludedEvent{
        - 		commonEvent: chainservice.commonEvent{
        - 			channelID: s"0x40c6f219558ae4d6dbe29b49096cb283a03be8e23191e8e40560708cecf17416",
        - 			BlockNum:  3,
        - 		},
        - 	},
        + 	chainservice.DepositedEvent{
        + 		commonEvent: chainservice.commonEvent{
        + 			channelID: s"0x40c6f219558ae4d6dbe29b49096cb283a03be8e23191e8e40560708cecf17416",
        + 			BlockNum:  2,
        + 		},
        + 		assetAndAmount: chainservice.assetAndAmount{AssetAmount: s"3"},
        + 		NowHeld:        s"3",
        + 	},
          )
--- FAIL: TestConcludeSimulatedBackendChainServiceWithPolling (0.09s)